// <auto-generated />
namespace Solita.RedirectManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class RequestHostAndPath : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RequestHostAndPath));
        
        string IMigrationMetadata.Id
        {
            get { return "201512011308001_RequestHostAndPath"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
